"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _EnrollmentFixed from './EnrollmentFixed.bones.json'
import _maintenance_page from './maintenance-page.bones.json'
import _EnrollmentSection from './EnrollmentSection.bones.json'

configureBoneyard({"color":"#f0f0f0","darkColor":"#2a2a2a","animate":"pulse","speed":"1.8s"})

registerBones({
  "EnrollmentFixed": _EnrollmentFixed,
  "maintenance-page": _maintenance_page,
  "EnrollmentSection": _EnrollmentSection,
})
