"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _EnrollmentFixed from './EnrollmentFixed.bones.json'

configureBoneyard({"color":"#f0f0f0","darkColor":"#2a2a2a","animate":"pulse","speed":"1.8s"})

registerBones({
  "EnrollmentFixed": _EnrollmentFixed,
})
